all:
  io_page:
    ioBlog:
      display:
        "Basic":    [title, slug, teaser, published_at]
        "Meta":     [tags, meta_keywords, meta_description]

  io_blog:
    web_dir:   '/ioBlogPlugin',